# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pokemon Review APP Build and Test
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: | 
        dotnet restore ./PokemonReviewApp/PokemonReviewApp.csproj
        dotnet restore ./PokemonReviewApp.Tests/PokemonReviewApp.Tests.csproj
    - name: Build
      run: |
        dotnet build --no-restore ./PokemonReviewApp/PokemonReviewApp.csproj
        dotnet build --no-restore ./PokemonReviewApp.Tests/PokemonReviewApp.Tests.csproj
    - name: Test
      run: dotnet test ./PokemonReviewApp.Tests/PokemonReviewApp.Tests.csproj --no-build --verbosity normal